language: minimal

dist: bionic

env:
  global:
    - REGISTRY_URL: "docker.io"  # docker.io or other registry URL, DOCKER_REGISTRY_USER/DOCKER_REGISTRY_PASSWORD to be set in CI env.
    - CI_PROJECT_NAME: "qpod"

install:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json && sudo service docker restart

before_script:
  - echo IP=$(curl -s http://ifconfig.me/ip)
  - docker info
  - CI_PROJECT_NAMESPACE=$([[ "$TRAVIS_PULL_REQUEST_SLUG" = "" ]] && echo "$(dirname ${TRAVIS_REPO_SLUG})" || echo "$(dirname ${TRAVIS_PULL_REQUEST_SLUG})")
  - export REPOSITORY=$(echo "${REGISTRY_URL}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}" | awk '{print tolower($0)}')
  - build_image_squash() { TAG=$1; FILE=$2; shift 2; docker build --squash --force-rm=true -t "${REPOSITORY}:$TAG" -f "$FILE" "$@" "$(dirname $FILE)"; }
  - build_image() { TAG=$1; FILE=$2; shift 2; docker build --force-rm=true -t "${REPOSITORY}:$TAG" -f "$FILE" "$@" "$(dirname $FILE)"; }
  - alias_image() { docker tag "${REPOSITORY}:$1" "${REPOSITORY}:$2"; }

after_script:
  - docker image prune --force && docker images
  - if [ "$TRAVIS_BRANCH" != "master" ]
      export REPOSITORY="${REPOSITORY}-${TRAVIS_BRANCH}"
    fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then
      echo "$DOCKER_REGISTRY_PASSWORD" | docker login "${REGISTRY_URL}" -u "$DOCKER_REGISTRY_USER" --password-stdin;
      docker push "${REPOSITORY}";
      status=$?;
      echo "[${status}] Image pushed > ${REPOSITORY}";
    else
      echo "Not pushing ${REPOSITORY} in PR ...";
    fi

stages:
  - elasticsearch

jobs:
  include:
    - name: elasticsearch
      stage: elasticsearch
      script:
        - build_image_squash "${TRAVIS_JOB_NAME}" "elasticsearch/Dockerfile" --build-arg "ES_VERSION=7.8.0"
        - build_image_squash "${TRAVIS_JOB_NAME}" "elasticsearch/Dockerfile" --build-arg "ES_VERSION=7.8.1"

notifications:
  slack: q-pod:lrzKf5Ff1Ao1MGclzElR23j4
